language: python
python:
- '3.6'
install:
- pip3 install ansible==2.5.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: F1neSSjrjRJL7arecYh4UCm0WgX7phCSWSKxaxkfdfzOtIflAzYUKZqAu7DobuPqIV6Bl+z3EhRFNyEIshZp+Z8IUBCeDWzKyFf0lwZLgOmT+XQbL8a6hxsGOYBUfG3LBpPbXg0JYfXXONskyt4kIXO4vIwxe91+VcOw5GaFPl1cSJnMrHohMkhNFXb5B43NfX6ARU8PgeO+vDZL5LD1oqmeVSfh6FoDnndZ/j8JA/FScthsteD3fhbPvISbdU2vc+552VA87n3i/rta65NyBaMGABYoUxg3d69RIpLvfABabTi1MQSW+Q/2WIOEVCPowzkidohktGWMwgVAWGQfbP+uCN5ZwJSxRGaLwNCK8BkGkZGpLRShKHUev+4+0XwT1D6ZJCZzrnTaEzWTa6wlfK05xVDjBIITfe4RmMgyUs982oeFTi7xPaXpYcQd2ENRW2ieffH/R9YV8ktuXbVRWaOP7v/ZVOh6kEkULQCVVvivZ+KN08/C7+g2vlCwSdakXu4ke22OqK+pZTgnH7/6XWcTshyaE4jbDVRuhnhuFwDQYWQ51bFKfRXUNQKKE3Dw3XUubAgEHD94ubLEdnmqGR7Kme5fxgVZ0M6givie/I/JG07rAkY1mDgKB978C0Hhn7fKRvBXD6QCpqdZ2CvRTYJRQbhexkiukrunX99DHHs=
  - secure: CswXwzaPkvS4x0aOurSath0uJEPEPIM3AyBECPQe8sISAfEfbKNoPC16PQHD2LfXEGCMgbeW0TCOnW2beiS4/4IZ4dLKpHsm5GSPlczTbddcSWMqxn67cjYT7+28c/mc0FRVmm4ZPlp2hmT5Z9kOa2jN5zajzfgZHN5XFmfrIpyviNfcMxriQe1TGsLgHRR5sn8t3fqkQAK6ZTNd9EpSCBMIExec5VF95vExp5wDT3+eXNaQh39FxdxajiRFa9IDmZD6sTibU5cjhIdQAakVht+7UhNT++xpHojQltEEt801dnV5aD9m6Ag82iSOz5+xAHobFsaFt9d1WNAmWJXTOi08XdG6IsCmMBkzeoz2AFUVNxCS07S3gSaBzrI8FD5adCvwA7XQ1tbB+Kw5zjJMDsjmppgVjafQDg8bONU3rSjB0kgY3yFIUFjIhMfVdj1Yi8fTlErnnDyWHbVKr6Zewc0t6IAODFnmpqjzdBtcCUn7UFgMYkZ5C+f5i4amcIbyv0SYpy/iIv1ZIcBk5Q2A2UELof4s3zR8yISV6nPt+AJ1XdfvNqTvkC3IvkSNAASZWUWelFwJBk8XCruSxcIusnY1NKQKBH6Z2Z4Ppk0Y0HNzld4oJtHmGXYqNC+XQvW/84jgL/vbsHkGPmr86cXwnx5cPhGO1bwEthyi6DSnHiE=
  - secure: OC8rCgVnlRJK1Cy7NycL1SKYhNrSaxxHk/t54ndiQfbGcyXqgI0Ac3hWY5WA5GKoQ1wUtxXaFkALMRqkdd//4Z3svxe1FyRi5B5mo1Pj7FVzDf4TUVc1CEGyFyKkPrBniEh3H834u/tdORn4zaWlfF08qQ99UEXn9DKgl3ixM/v9dYWcKARoARTX+5iTkFtq9tnck2GGC1t2X82XDLSi+vVAMiFUbDtdebXA8Uv+vDTqJ2pYjvUhBPI8cqwdZi0hwuepAvTjXSDBK4+LZ2OeAaX7Y8Uz+MPEzeoTTUFrN9pfYPTTSwa5jYs//hu9JCeG5rR+YmWM1X2lURvSiYVCBnejFydhpB//DADFIzu9ZYW4opnd+1wtgawYIx7ObBgUNx8zUTJdc8b6Jw+ol+zHi1RKALbE7A4gy4lpqHZg55vpCoWpBE1+qBfqpWI3n7nbo3fAcnsqPd9/r/kiyU5MXr0/pv+RhO/eE6BJIdxyZBfDqoAV0SnGgelr1rfA3rvVRfxaoxHD7srcmCrKQT77hACElQf5oK4KJoro7IdfJ0eBpGTbeuvbK3d0Sa1ld4tESjar2nCgqoYJvcAlDlAlGLkr6pEuwxGXtzSQRpxybf/uZpf7Bae9a1c6PVLR0WQ/FVSW4u0Huk96nW8td/H7DmBJKjKdMfBl5n9NGsLImVk=
script:
- molecule create --scenario-name travis
- molecule converge --scenario-name travis
- molecule verify --scenario-name travis
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_77c68a28addc_key -iv $encrypted_77c68a28addc_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
